In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [5]:
data=pd.read_csv(r'/content/mobile_price_classification.csv')

In [6]:
data.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam  4G  int_memory  \
0            842          0          2.2         0          1   0           7   
1           1021          1          0.5         1          0   1          53   
2            563          1          0.5         1          2   1          41   
3            615          1          2.5         0          0   0          10   
4           1821          1          1.2         0         13   1          44   

   m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0    0.6        188        2  ...         20       756  2549     9     7   
1    0.7        136        3  ...        905      1988  2631    17     3   
2    0.9        145        5  ...       1263      1716  2603    11     2   
3    0.8        131        6  ...       1216      1786  2769    16     8   
4    0.6        141        2  ...       1208      1212  1411     8     2   

   talk_time  three_g  touch_screen  wifi  price_range  
0         19        0             0     1            1  
1          7        1             1     0            2  
2          9        1             1     0            2  
3         11        1             0     0            2  
4         15        1             1     0            1  

[5 rows x 21 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   battery_power   2000 non-null   int64  
 1   bluetooth       2000 non-null   int64  
 2   clock_speed     2000 non-null   float64
 3   dual_sim        2000 non-null   int64  
 4   front_cam       2000 non-null   int64  
 5   4G              2000 non-null   int64  
 6   int_memory      2000 non-null   int64  
 7   m_dep           2000 non-null   float64
 8   mobile_wt       2000 non-null   int64  
 9   n_cores         2000 non-null   int64  
 10  primary_camera  2000 non-null   int64  
 11  px_height       2000 non-null   int64  
 12  px_width        2000 non-null   int64  
 13  ram             2000 non-null   int64  
 14  sc_h            2000 non-null   int64  
 15  sc_w            2000 non-null   int64  
 16  talk_time       2000 non-null   int64  
 17  three_g         2000 non-null   i

In [8]:
data.isna().sum()

battery_power     0
bluetooth         0
clock_speed       0
dual_sim          0
front_cam         0
4G                0
int_memory        0
m_dep             0
mobile_wt         0
n_cores           0
primary_camera    0
px_height         0
px_width          0
ram               0
sc_h              0
sc_w              0
talk_time         0
three_g           0
touch_screen      0
wifi              0
price_range       0
dtype: int64

In [9]:
data['price_range'].unique()

array([1, 2, 3, 0])

In [10]:
data1=data.drop(['price_range'],axis=1)

In [11]:
x=data1
y=data['price_range']

In [12]:
x.head()

battery_power  bluetooth  clock_speed  dual_sim  front_cam  4G  int_memory  \
0            842          0          2.2         0          1   0           7   
1           1021          1          0.5         1          0   1          53   
2            563          1          0.5         1          2   1          41   
3            615          1          2.5         0          0   0          10   
4           1821          1          1.2         0         13   1          44   

   m_dep  mobile_wt  n_cores  primary_camera  px_height  px_width   ram  sc_h  \
0    0.6        188        2               2         20       756  2549     9   
1    0.7        136        3               6        905      1988  2631    17   
2    0.9        145        5               6       1263      1716  2603    11   
3    0.8        131        6               9       1216      1786  2769    16   
4    0.6        141        2              14       1208      1212  1411     8   

   sc_w  talk_time  three_g  touch_screen  wifi  
0     7         19        0             0     1  
1     3          7        1             1     0  
2     2          9        1             1     0  
3     8         11        1             0     0  
4     2         15        1             1     0

In [13]:
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
y_train

968     1
240     2
819     0
692     3
420     1
       ..
1130    3
1294    0
860     2
1459    3
1126    1
Name: price_range, Length: 1600, dtype: int64

In [16]:
from keras.models import Sequential
from keras.layers import Dense

In [17]:
model=Sequential()

In [18]:
data['price_range'].unique()

array([1, 2, 3, 0])

In [19]:
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(4,activation='softmax'))

In [20]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='nadam',metrics=['accuracy'])

In [21]:
model.fit(x_train,y_train,epochs=20)

Epoch 1/20
50/50 [==============================] - 5s 3ms/step - loss: 67.7009 - accuracy: 0.3194
Epoch 2/20
50/50 [==============================] - 0s 2ms/step - loss: 7.1272 - accuracy: 0.4831
Epoch 3/20
50/50 [==============================] - 0s 2ms/step - loss: 4.6443 - accuracy: 0.4863
Epoch 4/20
50/50 [==============================] - 0s 3ms/step - loss: 3.8664 - accuracy: 0.5238
Epoch 5/20
50/50 [==============================] - 0s 3ms/step - loss: 3.3126 - accuracy: 0.5275
Epoch 6/20
50/50 [==============================] - 0s 2ms/step - loss: 2.9983 - accuracy: 0.5412
Epoch 7/20
50/50 [==============================] - 0s 3ms/step - loss: 2.6175 - accuracy: 0.5462
Epoch 8/20
50/50 [==============================] - 0s 2ms/step - loss: 2.4964 - accuracy: 0.5587
Epoch 9/20
50/50 [==============================] - 0s 2ms/step - loss: 2.5493 - accuracy: 0.5519
Epoch 10/20
50/50 [==============================] - 0s 2ms/step - loss: 2.2864 - accuracy: 0.5694
Epoch 11/20
50/50 

In [22]:
y_pred=np.argmax(model.predict(x_test),axis=1)

13/13 [==============================] - 0s 2ms/step


In [23]:
y_pred

array([0, 3, 1, 3, 1, 3, 3, 2, 3, 3, 0, 2, 2, 3, 3, 0, 3, 3, 2, 0, 0, 1,
       2, 2, 1, 1, 2, 2, 2, 0, 1, 1, 3, 0, 3, 3, 3, 2, 3, 0, 3, 3, 3, 0,
       3, 3, 1, 1, 3, 1, 3, 3, 0, 0, 3, 2, 1, 2, 0, 0, 2, 3, 3, 1, 2, 0,
       3, 3, 2, 2, 3, 1, 0, 1, 3, 0, 0, 3, 2, 3, 3, 2, 3, 0, 2, 3, 2, 3,
       3, 0, 3, 3, 3, 2, 3, 3, 2, 3, 3, 1, 0, 0, 1, 0, 1, 3, 3, 0, 1, 2,
       0, 1, 3, 1, 3, 2, 3, 3, 0, 3, 3, 3, 3, 3, 3, 3, 0, 3, 0, 2, 3, 1,
       2, 0, 0, 3, 2, 2, 3, 3, 3, 0, 3, 3, 0, 0, 0, 1, 1, 2, 3, 2, 1, 0,
       2, 3, 0, 1, 0, 1, 3, 3, 3, 3, 1, 0, 1, 3, 2, 3, 3, 1, 0, 0, 3, 2,
       2, 3, 2, 0, 0, 0, 0, 1, 3, 2, 0, 3, 0, 0, 0, 0, 3, 3, 3, 1, 0, 1,
       3, 0, 1, 3, 2, 3, 3, 2, 1, 3, 0, 0, 0, 2, 2, 1, 3, 1, 2, 3, 3, 2,
       3, 2, 0, 0, 0, 2, 0, 2, 0, 0, 2, 0, 2, 3, 1, 1, 1, 3, 3, 3, 3, 3,
       3, 3, 0, 3, 3, 3, 3, 3, 3, 0, 1, 3, 3, 1, 3, 3, 3, 2, 3, 0, 3, 2,
       3, 2, 3, 0, 3, 2, 3, 3, 3, 2, 0, 3, 0, 3, 3, 1, 2, 2, 0, 3, 2, 3,
       0, 0, 3, 1, 2, 2, 3, 3, 3, 1, 1, 0, 2, 3, 3,

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test,y_pred)

0.62